services:
  a1111:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    image: ghcr.io/tsondo/a1111-docker:latest
    container_name: a1111
    ports:
      - "7860:7860"
    volumes:
      - ./config.json:/workspace/stable-diffusion-webui/config.json
      - ./ui-config.json:/workspace/stable-diffusion-webui/ui-config.json
      - ./styles.csv:/workspace/stable-diffusion-webui/styles.csv
      - ${MODEL_DIR:-./models}:/workspace/stable-diffusion-webui/models
      - ${OUTPUT_DIR:-./outputs}:/workspace/stable-diffusion-webui/outputs
      - ${EXT_DIR:-./extensions}:/workspace/stable-diffusion-webui/extensions
      - ${EMBEDDINGS_DIR:-./embeddings}:/workspace/stable-diffusion-webui/embeddings
      - ${LOGS_DIR:-./logs}:/workspace/stable-diffusion-webui/logs
      - ${CACHE_DIR:-./cache}:/workspace/stable-diffusion-webui/cache
      - ${PIP_CACHE_DIR:-./pip-cache}:/workspace/stable-diffusion-webui/pip-cache
    environment:
      - COMMANDLINE_ARGS=--xformers --enable-insecure-extension-access --listen --port 7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
        limits:
          memory: 32g
    restart: on-failure:5
